apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  PORT: "3001"
  NODE_ENV: development
  USER_SERVICE_URL: http://user-service:3002
  MONGO_URI: mongodb://admin:password_123@mongodb:27017/training_auth_db?authSource=admin
  JWT_SECRET: supersecret_jwt_key_change_in_production