apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    blueGreen:
      activeService: {{ .Chart.Name }}
      previewService: {{ .Chart.Name }}-preview
      autoPromotion: false
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        rollout: preview
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:                          # ← ADD THIS
        - configMapRef:
            name: {{ .Chart.Name }}-config
        - secretRef:
            name: {{ .Chart.Name }}-secret