apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXRfand0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbg==
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkXzEyM0Btb25nb2RiOjI3MDE3L3RyYWluaW5nX2F1dGhfZGI/YXV0aFNvdXJjZT1hZG1pbg==