image: nimeshsv814/ld-api-gateway:v1.0.2
replicas: 1
port: 3000
namespace: dev
env:
  REDIS_URL: redis://redis:6379
  AUTH_SERVICE_URL: http://auth-service:3001
  USER_SERVICE_URL: http://user-service:3002
  TRAINING_SERVICE_URL: http://training-service:3003
  ATTENDANCE_SERVICE_URL: http://attendance-service:3004
  NOTIFICATION_SERVICE_URL: http://notification-service:3005
# Default dev/test values for api-gateway