apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-preview
spec:
  selector:
    app: {{ .Chart.Name }}
    rollout: preview
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP