namespace: dev
gateway:
  enabled: true
  name: kgateway
  namespace: dev
httproute:
  enabled: true
  name: kgateway-routes
  namespace: dev
storageClass:
  enabled: true
database:
  storageClassName: mongodb-storage-dev
  nfs:
    server: 10.0.8.33
    path: /var/nfs/general/lnd-test
mongodb:
  enabled: true
  name: mongodb
  namespace: dev
  replicas: 1
  storageSize: 10Gi
  user: admin
  password: password_123
# Default dev/test values for common infrastructure