namespace: prod
gateway:
  enabled: true
  name: kgateway
  namespace: prod
httproute:
  enabled: true
  name: kgateway-routes
  namespace: prod
storageClass:
  enabled: true
  name: mongodb-storage-dev        # ← moved here
  nfs:                             # ← moved here
    server: 10.0.8.33
    path: /var/nfs/general/lnd-test
mongodb:
  enabled: true
  name: mongodb
  namespace: prod
  replicas: 1
  storageSize: 50Gi
  user: admin
  password: password_123