apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attendance-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo
    targetRevision: main
    path: helm/services/attendance-service
    helm:
      releaseName: attendance-service
      values: values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true